### ISSUE TITLE
部分小说封面无法显示

### ISSUE THREAD

**Issue by asddaasdda** [wuyu8512/EbookReader-Xamarin#1]
通过导入文件夹的方法导入小说后发现有一部分封面无法显示，打开之后是正常的。只是在书架上是空白。

而单独导入书籍却没问题。
![Screenshot_2021-05-03-20-29-28-181_com acgdmzy ebookreader_Pic](https://user-images.githubusercontent.com/25479523/116875957-53e6e700-ac4e-11eb-9bc4-dba1fc7aecbf.png)

![Screenshot_2021-05-03-20-22-06-621_com acgdmzy ebookreader_Pic](https://user-images.githubusercontent.com/25479523/116875762-04a0b680-ac4e-11eb-9811-2b30165aee56.png)

**Comment by wuyu8512** [comment]
单独把epub文件拿到电脑上检查是否有设置封面
目前软件对封面的检测有两个步骤，不打开书籍的情况下，会按EPUB标准去查找封面，找不到就显示为空白
打开书籍的情况下，除了按正常标准查找，还会在找不到的情况下默读读取`/OEBPS/Images/cover.jpg`文件
所有你这种情况大概率是EPUB本身的问题

**Comment by asddaasdda** [comment]
解决了，需要重新添加一次封面。
